In [0]:
import torch

In [0]:
torch.zeros([3, 4]) # тензор 3*4 состоящий из 0

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [0]:
torch.ones([3, 4, 3])  # матрица из 1

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [0]:
x =torch.Tensor([[1, 2, 3], [4, 5, 6]])  # произвольный тензор
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [0]:
x.size()

torch.Size([2, 3])

In [0]:
x.shape

torch.Size([2, 3])

In [0]:
x[0, 2]

tensor(3.)

In [0]:
x[1, :]

tensor([4., 5., 6.])

In [0]:
x + 10

tensor([[11., 12., 13.],
        [14., 15., 16.]])

In [0]:
y =torch.Tensor([[10, 20, 30], [40, 50, 60]])  # произвольный тензор
y

tensor([[10., 20., 30.],
        [40., 50., 60.]])

In [0]:
x + y

tensor([[11., 22., 33.],
        [44., 55., 66.]])

In [0]:
x % y

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [0]:
torch.sin(x)

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.7568, -0.9589, -0.2794]])

In [0]:
x > 2

tensor([[False, False,  True],
        [ True,  True,  True]])

In [0]:
x[x>2]

tensor([3., 4., 5., 6.])

In [0]:
t = x  # передача по ссылке 
t

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [0]:
t = x.clone()  # копирование тензора
t

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [0]:
x.dtype   # тип данных в тензоре

torch.float32

In [0]:
x =x.double()  #  преобрзование типов внутри тензора
x.dtype

torch.float64

In [0]:
import numpy as np

In [0]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [0]:
x = torch.from_numpy(x)  # np.array в тензор torch

In [0]:
x

tensor([1, 2, 3])

In [0]:
# torch тензор в np.array
x = x.numpy()

In [0]:
x

array([1, 2, 3])

In [0]:
# Вычисление на GPU

In [0]:
x = torch.rand([2, 3])
x

tensor([[0.5651, 0.9950, 0.9380],
        [0.3541, 0.6389, 0.5312]])

In [0]:
torch.cuda.is_available()  # если false то нужно включить gpu в настройках колаба

True

In [0]:
torch.device('cuda:0')  # девайс отвечающий за видеокарту 0 

device(type='cuda', index=0)

In [0]:
torch.device('cpu') # перевод на cpu

In [0]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')  # универсальный код для машины

In [0]:
x_cuda = x.to(device)  # x_cuda хранится теперь на видеокарте

In [0]:
x_cuda

tensor([[0.5651, 0.9950, 0.9380],
        [0.3541, 0.6389, 0.5312]], device='cuda:0')

In [0]:
# Проверк скорости выполнение
%time 
y = (x - x + x * 10.0) **3

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 6.68 µs


In [0]:
%time 
y = (x_cuda - x_cuda + x_cuda * 10.0) **3

CPU times: user 2 µs, sys: 1e+03 ns, total: 3 µs
Wall time: 4.53 µs


In [0]:
# обычно ускорение на gpu заметно на больших тензорах